package com.laocuo.biyeban.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.laocuo.biyeban.greendao.Account;
import com.laocuo.biyeban.greendao.Messages;
import com.laocuo.biyeban.greendao.News;
import com.laocuo.biyeban.greendao.User;

import com.laocuo.biyeban.greendao.AccountDao;
import com.laocuo.biyeban.greendao.MessagesDao;
import com.laocuo.biyeban.greendao.NewsDao;
import com.laocuo.biyeban.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig messagesDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AccountDao accountDao;
    private final MessagesDao messagesDao;
    private final NewsDao newsDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        messagesDao = new MessagesDao(messagesDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Messages.class, messagesDao);
        registerDao(News.class, newsDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        messagesDaoConfig.clearIdentityScope();
        newsDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
