package com.laocuo.biyeban.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.laocuo.biyeban.greendao.Messages;
import com.laocuo.biyeban.greendao.User;
import com.laocuo.biyeban.greendao.News;

import com.laocuo.biyeban.greendao.MessagesDao;
import com.laocuo.biyeban.greendao.UserDao;
import com.laocuo.biyeban.greendao.NewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messagesDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig newsDaoConfig;

    private final MessagesDao messagesDao;
    private final UserDao userDao;
    private final NewsDao newsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        messagesDao = new MessagesDao(messagesDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);

        registerDao(Messages.class, messagesDao);
        registerDao(User.class, userDao);
        registerDao(News.class, newsDao);
    }
    
    public void clear() {
        messagesDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        newsDaoConfig.clearIdentityScope();
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

}
